Remove async/await from metrics
connectedcars/node-logutil pull request #36
Opened 2021-03-24 21:42 UTC by chribsen

It's not needed

2021-03-26 10:09 UTC, mathiastj approved these changes
When you do the major bump you should probably commit to updating every single repository that uses the async functions, so this will not be a constant frustration later.

2021-03-26 10:10 UTC, mathiastj requested changes
Need to update the types file `index.d.ts`

2021-04-06 12:24 UTC, chribsen commented
> you should probably commit to updating every single repository that uses the async functions, so this will not be a constant frustration later.

Agree

> Need to update the types file index.d.ts

Updated now

2021-04-06 12:29 UTC, mathiastj approved these changes

2021-06-10 11:18 UTC, mex approved these changes

2021-06-14 11:58 UTC, mex approved these changes

2021-06-14 12:08 UTC, merged